services:

  app:
    build:
      context: ./.
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - fast_api:/app/data
    depends_on:
      - elastic
      - redis

  elastic:
    image: elasticsearch:7.17.6
    environment:
      - discovery.type=single-node
      - ingest.geoip.downloader.enabled=false
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms200m -Xmx200m
    ports:
      - "9200:9200"
    restart: on-failure

  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"
    volumes:
      - redis_src:/app/redis/data

    etl:
      build: ./etl
      env_file:
        - .env.example
      command: tail -F anything
      depends_on:
        - postgres
        - elastic
      expose:
        - 8000

      postgres:
        image: postgres:13
        env_file:
          - .env.example
        volumes:
          - $HOME/postgresql/data:/var/lib/postgresql/data
        expose:
          - 5432
    #    ports:
    #      - '5432:5432'

volumes:
  fast_api:
  redis_src:

