services:

  elastic:
    image: elasticsearch:7.17.6
    environment:
      - discovery.type=single-node
      - ingest.geoip.downloader.enabled=false
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms200m -Xmx200m
    ports:
      - "9200:9200"
    expose:
      - 9200
    restart: on-failure

  postgres:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - $PWD/postgresql/data:/var/lib/postgresql/data
    expose:
      - 5432

  etl:
    build:
      context: ./etl
    env_file:
      - .env
    depends_on:
      - postgres
      - elastic

  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"
    volumes:
      - redis_src:/app/redis/data

volumes:
  redis_src:
